CREATE SEQUENCE IF NOT EXISTS seq_pk_local START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS seq_pk_evento START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS seq_pk_produto START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS seq_pk_estande START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS seq_pk_recibo START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS seq_pk_ingresso START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS seq_pk_atividade START WITH 1 INCREMENT BY 1 NOCACHE;
