CREATE SEQUENCE seq_pk_local START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pk_evento START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pk_produto START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pk_estande START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pk_cupom START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pk_recibo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pk_ingresso START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pk_atividade START WITH 1 INCREMENT BY 1;
